SELECT
    C.CustomerID,
    C.CompanyID,
    C.StoreId,
    C.CustomerNumber,
    C.FirstName,
    C.MiddleName,
    C.LastName,
    C.AddressLine1,
    C.AddressLine2,
    C.City,
    C.Country,
    C.State,
    C.ZipCode,
    C.Phone1,
    C.Phone2,
    LVID.Value AS IDTypeId,
    C.ID1StateIssueId,
    C.ID1ExpiryDate,
    C.ID1Number,
    LVID2.Value AS ID2TypeId,
    C.ID2ExpiryDate,
    C.ID2Number,
    C.IDAddressLine1,
    C.IDAddressLine2,
    C.IDCity,
    C.IDState,
    C.IDZipCode,
    C.CellPhone,
    C.Email,
    C.Height,
    C.Weight,
    LVH.Value AS Hair,
    LVE.Value AS Eyes,
    LVR.Value AS Race,
    LVS.Value AS Sex,
    C.BirthDate,
    C.BirthCity,
    C.BirthState,
    C.BirthCountry,
    C.Features,
    C.Comments,
    C.EmployeeName,
    C.EmpAddressLine1,
    C.EmpAddressLine2,
    C.EmpCity,
    C.EmpState,
    C.EmpZipCode,
    C.EmpPhone1,
    C.EmpPhone2,
    C.Military,
    C.Known,
    C.Referred,
    C.FedFirearmNumber,
    C.FedFirearmExpiryDate,
    C.VehicleMake,
    C.VehicleTagNumber,
    C.VehicleTagState,
    C.TexId,
    C.CustomerCredit,
    C.PreferredRate,
    C.IsDeleted,
    C.IsActive,
    C.CreatedDate,
    U.UserName AS CreatedBy,
    C.UpdatedDate,
    C.EmpCountry,
    C.AnniversaryDate,
    C.Form8300Date,
    C.LastTextDate,
    C.SendAccountingTexts,
    C.SendMarketingTexts,
    C.IsLocked,
    C.IsNeverSendRemindersLetter,
    C.IsOfACSDNList,
    C.IsNeverDisplayOfACWarning,
    C.IsDefault,
    C.IsPaymentLocked,
    C.PaymentLockedOn,
    C.PaymentLockedBy,
    C.PaymentLockedAt,
    C.IDCountry,
    C.IsMLARateApplied,
    C.BiometricSample,
    C.ID1IssueDate,
    C.ID2IssueDate,
    C.WebPortalAccess,
    C.WebPortalPin,
    C.LastMLAVerificationDate
FROM Customer C
LEFT JOIN LookupValue LVH ON LVH.LookupValueId = C.Hair
LEFT JOIN LookupValue LVE ON LVE.LookupValueId = C.Eyes
LEFT JOIN LookupValue LVR ON LVR.LookupValueId = C.Race
LEFT JOIN LookupValue LVS ON LVS.LookupValueId = C.Sex
LEFT JOIN LookupValue LVID ON LVID.LookupValueId = C.ID1TypeId
LEFT JOIN LookupValue LVID2 ON LVID2.LookupValueId = C.ID2TypeId
LEFT JOIN User U ON U.UserId = C.CreatedBy
